# Generated by Django 5.2.5 on 2025-08-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
