# Generated by Django 5.2.5 on 2025-08-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buhapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Username',
        ),
    ]
