# Generated by Django 5.2.5 on 2025-08-06 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buhapp', '0002_remove_users_email_remove_users_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Firstname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Lastname',
            new_name='Last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.EmailField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
