# Generated by Django 5.2.5 on 2025-08-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buhapp', '0003_rename_firstname_users_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
