# Generated by Django 5.2.5 on 2025-08-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buhapp', '0004_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Email', models.EmailField(default=True, max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
